### ISSUE TITLE
Way to know if the rate limit is unlimited

### ISSUE THREAD

**Issue by vzamanillo** [projectdiscovery/ratelimit#14]
Could be useful having a method to now when the rate limit is unlimited or not.

**Comment by tarunKoyalwar** [comment]
@vzamanillo  , can you share any use case perhaps this could be easily implemented.

**Comment by vzamanillo** [comment]
Maybe I am missing something but I think you can't currently know what was the raw input value for the rate limit nor when it is unlimited, would be useful to know that for checking when a rate limit is set / not set / overwritten.

Checking subfinder

![imagen](https://user-images.githubusercontent.com/10209695/207534790-48261fe8-e0ca-4067-b100-26f9a1127340.png)

after those lines of code the input raw value is lost.

Considering the `Limiter` is an object who mostly does his work based on an input integer value at least would expose a method to recover that value and (plus) to know when it was not set (unlimited).

Also I would change the way on how it is initialized, it's pretty weird having to check the input value to create a new instance of the limiter using `New` or `NewUnlimited,`   there should be a single initialize entry point with the necessary logic to know what to do and make the initialization abstract.
