### ISSUE TITLE
Race Condition in rate limit feature

### ISSUE THREAD

**Issue by DeadlyHollows** [projectdiscovery/ratelimit#30]
I had noticed a race condition in this code:

**Affected Code:**
https://github.com/projectdiscovery/ratelimit/blob/main/ratelimit.go#L23-L25

```
		if limiter.count == 0 {
			<-limiter.ticker.C
			limiter.count = limiter.maxCount
```

It is a TOCTOU (time-of-check to time-of-use) bug. The variable's value is read and then set in the if clause.
When using a multi-threaded application, this issue can be noticed.

I used Golang's `-race` flag to locate this issue.

**Comment by DeadlyHollows** [comment]
Hi, I still feel the fix isn't proper (but please correct me if am wrong):

**The fix:**
```
		if limiter.count.Load() == 0 {
			<-limiter.ticker.C
			limiter.count.Store(limiter.maxCount)
```

Issue is that load by itself is atomic and store by itself is atomic but the whole operation isn't atomic - the checking and updation of counter.

Let me paint a scenario to help me clarify my point.

Let's say we have 2 threads:

**Thread 1:** 
```
       if limiter.count.Load() == 0 {
->        <-limiter.ticker.C
            limiter.count.Store(limiter.maxCount)
        }
```

**Thread 2:** 
```
->    if limiter.count.Load() == 0 {
           <-limiter.ticker.C
           limiter.count.Store(limiter.maxCount)
        }
```

The arrows indicate where threads 1 and 2 respectively are.

They both can simultaneously pass the `if` checks and be inside the if and atomically save the max count value independently but atomically. This is a problem - the whole operation of check and store must be atomic.

That's why I think the fix is partial, and hasn't addressed the complete problem.

**Comment by Mzack9999** [comment]
@DeadlyHollows Thanks for the additional insights. The synchronism must be extended. I'm looking into this.

**Comment by Mzack9999** [comment]
@DeadlyHollows After checking the code, I believe there is no race condition here as the mentioned code (`ratelimit.run(..)`) runs atomically once per rate-limit instance, so there will never be concurrent go routines accessing the atomic counter. The only exposed methods take tokens from the buffered channel, which is handled internally in singleton mode. Please let me know if this makes sense to you. Thanks!

**Comment by DeadlyHollows** [comment]
Ah makes perfect sense 👌
Thanks @Mzack9999 and @ehsandeep. Appreciate your help with this.

Cheers!
