### ISSUE TITLE
change limit on fly?

### ISSUE THREAD

**Issue by parsibox** [projectdiscovery/ratelimit#47]
hi
how can change limit after run?
for example i want start with 100 limit and after some work i change it to 500 limit

**Comment by Mzack9999** [comment]
@parsibox It's currently not possible, we started a prototype implementation which is actually commented out. I tracked the functionality at https://github.com/projectdiscovery/ratelimit/issues/64

**Comment by Mzack9999** [comment]
Closing - Tracked at https://github.com/projectdiscovery/ratelimit/issues/64
