### ISSUE TITLE
Add missing test edge cases

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/ratelimit#8]
## Description
The bits size of the internal counter might create platform compatibility issues. The scope of this issue is to update the existing testing workflow to support multiple operative systems and architectures bits:
- [x] Update [build-test.yml](https://github.com/projectdiscovery/ratelimit/blob/main/.github/workflows/build-test.yml) to support multiple operative systems (eg. windows, ubuntu, osx) and architectures (amd64, 386, arm)

**Comment by xm1k3** [comment]
#12
